version: '3.7'
services:
  php:
    container_name: php_${PROJECT_NAME}
    restart: always
    build:
      context: .docker/fpm
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=$IP_HOST xdebug.discover_client_host=0 idekey=PHPSTORM"
    links:
      - db
    volumes:
      - ./:/var/www
  nginx:
    container_name: nginx_${PROJECT_NAME}
    restart: always
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    volumes:
      - ./:/var/www
    depends_on:
      - php
  rabbitmq:
    build:
      context: .
      dockerfile: .docker/rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5  
  db:
    container_name: db_${PROJECT_NAME}4
    restart: always
    image: mysql:8.0
    command: ['--default-authentication-plugin=mysql_native_password', '--sql-mode=', '--net_read_timeout=360', '--net_write_timeout=360']
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ~/.mysql_db:/var/lib/mysql:rw
networks:
  default:
    name: network
